language: go
sudo: required
go:
  - 1.5.2

env:
    matrix:
       - GIMME_OS=windows GIMME_ARCH=amd64
       - GIMME_OS=linux GIMME_ARCH=amd64
       - GIMME_OS=linux GIMME_ARCH=386
       - GIMME_OS=darwin GIMME_ARCH=amd64
    global:
       - secure: "GxXEKlRPKZMsyNIexmX02lVEdUMr/GiTXs7WsVI1KF3UOQqpQ89lHN4xxSKtnYRKf8uRgP/2gDlkeZZIITIUoace33ltRFzaTM6x+A+nm1pUh29tUtcCZ/7Y57H3mbJHuzulRafATxVfp3wV76+eOgbMwdPzT1UwzlL79XQKLHH2yamqux0ORMGoMAvphCbmVcmpoZLI6QzWkzPkpCf+TvOkj+boxEhpJnfVOk0vgxOwFx08gh8svQiYWtuA7IBjoVl4qwN5QvrKD7UiZCOAu1a5fF+dTLynNp4I63UbRGc/mhESLYuYnM4xMstJHYNW3NqzbbIccr71MouAh8UMGG7Laz0WxiMYlKIAs7qy+am8tgsllSseinExi70CMo7SR3uXzyb69KtPjy3kBnzvetKdXhghml6jwx5l2q4GkFuu7HaIvOCFxqqihj4QAMY5N5faDOdInBnXO5mMQnev3R6PiPCttuT9+OqsLORf78HYbOUmOvBr9qychleMKC9vJfz55vwtbdy49u+f/hYKdxVMv5Lhbl50NE3BmaciZ4NyyUaWGRK4BihyHAVTnY4iuODzazFLFytl2h/D/7p1t7TFPetDMkInxmrol0RiBfXO0l5OO8Yga40cowStOkpUQDnw8AjQW2T99HjmeJHF5N11n8OoXUBmwhO6WcF7Mq4="

after_script:
  - ls -l ../../../../bin

deploy:
  skip_cleanup: true
  file: bintray_descriptors/${GIMME_OS}_${GIMME_ARCH}.json
  provider: bintray
  key: $API_KEY
  passphrase: aaa
  user: jfrogdev